"""Canonical entities and operand normalization for the comment graph.

Pure module: no I/O, no third-party deps. Everything here is a value type so it
can be hashed into graph nodes, fact subjects, and dedup sets.

Operand identity rule (mirrors ``LadderInstruction.get_primary_tag`` in
``src/ladder_renderer/ladder_to_dot.py`` :84): the *base tag* of an operand is
its leading identifier stripped of the first ``[index]`` or ``.member``
expression, whichever comes first. The *operand* itself keeps the exact member/
index expression, so ``N101[18]`` and ``N101[20].1`` are distinct operands that
both belong to ``tag:N101``.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from enum import Enum
from typing import Optional


class EntityKind(Enum):
    """Kinds of nodes in the dependency graph. The value is the id prefix."""

    TAG = "tag"          # a controller/program tag, base identity of operands
    OPERAND = "op"       # an exact operand expression (member/index preserved)
    RUNG = "rung"        # one ladder rung: program/routine/number
    MODULE_IO = "io"     # a module I/O connection point (reserved; see edges)


class Confidence(Enum):
    """Ordered confidence levels. Higher value = more certain."""

    LOW = 1
    MEDIUM = 2
    HIGH = 3

    def stepped_down(self) -> "Confidence":
        """One level lower, floored at LOW (used when propagating along FEEDS)."""
        return Confidence(max(1, self.value - 1))


# A literal (immediate) operand: a number, or a single-quoted string. These are
# never tags and get no operand entity.
_NUMBER_RE = re.compile(r"^[-+]?(\d+\.?\d*|\.\d+)([eE][-+]?\d+)?$")


def is_literal(operand: str) -> bool:
    """True when ``operand`` is an immediate constant, not a tag reference."""
    text = operand.strip()
    if not text:
        return False
    if text[0] in "'\"":
        return True
    return bool(_NUMBER_RE.match(text))


# Markers a migration tool leaves in place of a real, human-authored comment.
# Such text carries no engineering meaning and must NOT be treated as an
# authoritative native comment; the operand is effectively uncommented.
_PLACEHOLDER_MARKERS = ("generated by migration tool",)


def is_placeholder_comment(text: Optional[str]) -> bool:
    """True when a comment is migration-generated placeholder text, not real."""
    if not text:
        return False
    lowered = text.lower()
    return any(marker in lowered for marker in _PLACEHOLDER_MARKERS)


def normalize_operand(operand: str) -> str:
    """Canonicalize an operand's textual form without losing identity.

    Strips surrounding whitespace and any whitespace inside ``[...]`` subscripts
    (Studio 5000 export never contains it, but hand-authored snippets may). The
    member/index expression is otherwise preserved verbatim.
    """
    text = operand.strip()
    # Remove whitespace immediately inside square-bracket subscripts.
    text = re.sub(r"\[\s*([^\]]*?)\s*\]", lambda m: "[" + re.sub(r"\s+", "", m.group(1)) + "]", text)
    return text


def base_tag_of(operand: str) -> str:
    """Return the base tag identity of an operand.

    The base tag is the operand up to (but excluding) the first ``.`` member or
    ``[`` index expression. Module I/O paths keep their ``Name:Slot:Type``
    connection prefix, since the colons precede the first member dot.
    """
    text = normalize_operand(operand)
    # First occurrence of a member dot or an index bracket ends the base tag.
    cut = len(text)
    for ch in (".", "["):
        idx = text.find(ch)
        if idx != -1:
            cut = min(cut, idx)
    return text[:cut]


@dataclass(frozen=True)
class EntityId:
    """A hashable, canonical identifier for a graph node."""

    kind: EntityKind
    key: str

    def __str__(self) -> str:
        return f"{self.kind.value}:{self.key}"


@dataclass(frozen=True)
class SourceLoc:
    """Where in the L5X a fact/edge came from. All fields optional."""

    program: Optional[str] = None
    routine: Optional[str] = None
    rung: Optional[int] = None
    operand: Optional[str] = None


@dataclass(frozen=True)
class Entity:
    """A node's identity plus light metadata for reporting."""

    id: EntityId
    display: str = ""
    base_tag: Optional[EntityId] = None


def operand_entity(operand: str) -> EntityId:
    """EntityId for an exact operand expression (whitespace-normalized)."""
    return EntityId(EntityKind.OPERAND, normalize_operand(operand))


def tag_entity(name: str) -> EntityId:
    """EntityId for a base tag."""
    return EntityId(EntityKind.TAG, name.strip())


def rung_entity(program: str, routine: str, number: int) -> EntityId:
    """EntityId for a rung, keyed ``program/routine/number``."""
    return EntityId(EntityKind.RUNG, f"{program}/{routine}/{number}")


def module_io_entity(path: str) -> EntityId:
    """EntityId for a module I/O connection point (base identity of the path)."""
    return EntityId(EntityKind.MODULE_IO, base_tag_of(path))
