"""Unit tests for canonical entities and operand normalization (Checkpoint 1)."""

from comment_graph.model import (
    EntityKind,
    EntityId,
    SourceLoc,
    normalize_operand,
    base_tag_of,
    is_literal,
    is_placeholder_comment,
    operand_entity,
    tag_entity,
    rung_entity,
)


class TestIsPlaceholderComment:
    def test_exact_migration_marker(self):
        assert is_placeholder_comment("Generated by Migration Tool")

    def test_case_insensitive(self):
        assert is_placeholder_comment("GENERATED BY MIGRATION TOOL")

    def test_marker_embedded_in_larger_text(self):
        assert is_placeholder_comment("N101[18] - Generated by Migration Tool v3")

    def test_real_comment_is_not_placeholder(self):
        assert not is_placeholder_comment("Thawing Room 1 RTD A Calibrated Temperature")

    def test_empty_is_not_placeholder(self):
        assert not is_placeholder_comment("")
        assert not is_placeholder_comment(None)


class TestNormalizeOperand:
    def test_strips_surrounding_whitespace(self):
        assert normalize_operand("  N101[18] ") == "N101[18]"

    def test_collapses_internal_whitespace_in_subscript(self):
        assert normalize_operand("N101[ 18 ]") == "N101[18]"

    def test_preserves_member_and_index_expression(self):
        assert normalize_operand("N101[20].1") == "N101[20].1"

    def test_preserves_module_io_path(self):
        assert (
            normalize_operand("ENETBRIDGE_5069:1:I.Ch00.Data")
            == "ENETBRIDGE_5069:1:I.Ch00.Data"
        )


class TestBaseTagOf:
    def test_array_element(self):
        assert base_tag_of("N101[18]") == "N101"

    def test_array_element_with_bit_member(self):
        assert base_tag_of("N101[20].1") == "N101"

    def test_udt_member(self):
        assert base_tag_of("DR1_MY_001.PER_ILK") == "DR1_MY_001"

    def test_module_io_keeps_connection_prefix(self):
        # The base identity of a module I/O point is its connection tag,
        # i.e. everything up to the first member/element expression.
        assert base_tag_of("ENETBRIDGE_5069:1:I.Ch00.Data") == "ENETBRIDGE_5069:1:I"

    def test_plain_tag(self):
        assert base_tag_of("Running") == "Running"


class TestIsLiteral:
    def test_integer_literal(self):
        assert is_literal("1")

    def test_negative_and_float_literal(self):
        assert is_literal("-3")
        assert is_literal("2.5")

    def test_tag_is_not_literal(self):
        assert not is_literal("N101[18]")

    def test_string_literal(self):
        assert is_literal("'hello'")


class TestEntityId:
    def test_str_form_uses_kind_prefix(self):
        assert str(operand_entity("N101[18]")) == "op:N101[18]"
        assert str(tag_entity("N101")) == "tag:N101"

    def test_operand_and_tag_are_distinct(self):
        assert operand_entity("N101") != tag_entity("N101")

    def test_hashable_and_value_equal(self):
        a = operand_entity(" N101[18] ")
        b = operand_entity("N101[18]")
        assert a == b
        assert len({a, b}) == 1

    def test_rung_entity_key(self):
        rid = rung_entity("MainProgram", "MainRoutine", 3)
        assert rid.kind is EntityKind.RUNG
        assert str(rid) == "rung:MainProgram/MainRoutine/3"

    def test_distinct_operands_distinct_ids(self):
        assert operand_entity("N101[18]") != operand_entity("N101[20].1")


class TestSourceLoc:
    def test_carries_program_routine_rung(self):
        loc = SourceLoc(program="MainProgram", routine="MainRoutine", rung=3)
        assert (loc.program, loc.routine, loc.rung) == ("MainProgram", "MainRoutine", 3)
