"""Convergence-behavior tests for the orchestrator on synthetic L5X (Ckpt 5)."""

import asyncio

from comment_graph.model import operand_entity
from comment_graph.config import AnalysisConfig, AnalysisRequest, ConvergenceStatus
from comment_graph.orchestrator import analyze_comment_graph

from tests.comment_graph.conftest import rung_xml, tag_xml


def _run(path, **kwargs):
    request = AnalysisRequest(file_path=str(path), **kwargs)
    return asyncio.run(analyze_comment_graph(request))


def _decision_for(result, name):
    return next((d for d in result.decisions if d["NAME"] == name), None)


class TestMultipassChain:
    def test_comment_propagates_backward_over_passes(self, l5x_factory):
        # A -> B -> C, native comment on C. Requires >1 pass to reach A.
        path = l5x_factory(
            tags_xml=tag_xml("C", operand_comments={"": "calibrated temperature"}),
            rungs_xml=rung_xml(0, "MOV(A,B);") + rung_xml(1, "MOV(B,C);"),
        )
        result = _run(path)
        assert _decision_for(result, "B") is not None
        assert _decision_for(result, "A") is not None
        assert len(result.pass_history) >= 2


class TestDiamond:
    def test_forward_propagation_reaches_sink(self, l5x_factory):
        # A feeds B and C; B and C feed D; native comment on A.
        path = l5x_factory(
            tags_xml=tag_xml("A", operand_comments={"": "source flow"}),
            rungs_xml=(
                rung_xml(0, "MOV(A,B);")
                + rung_xml(1, "MOV(A,C);")
                + rung_xml(2, "ADD(B,C,D);")
            ),
        )
        result = _run(path)
        assert _decision_for(result, "D") is not None


class TestCycleBounded:
    def test_cycle_without_comment_escalates_not_fabricates(self, l5x_factory):
        path = l5x_factory(rungs_xml=rung_xml(0, "MOV(A,B);") + rung_xml(1, "MOV(B,A);"))
        result = _run(path)
        assert result.convergence_status is ConvergenceStatus.PARTIAL
        assert result.assistance_requests
        assert all(
            r["suggested_model_level"] == "opus" for r in result.assistance_requests
        )


class TestUnsupportedInstruction:
    def test_warns_and_does_not_invent_direction(self, l5x_factory):
        path = l5x_factory(rungs_xml=rung_xml(0, "FOOBAR(X,Y);"))
        result = _run(path)
        assert any("FOOBAR" in w for w in result.warnings)
        assert result.convergence_status is ConvergenceStatus.PARTIAL


class TestContradiction:
    def test_weaker_user_seed_contradicts_native_comment(self, l5x_factory):
        path = l5x_factory(
            tags_xml=tag_xml("N101", operand_comments={"[18]": "temperature"}),
            rungs_xml=rung_xml(0, "MOV(N101[18], Dest);"),
        )
        result = _run(
            path,
            user_seeds=[{"NAME": "N101[18]", "PROPOSED_DESCRIPTION": "pressure"}],
        )
        assert result.contradictions
        c = result.contradictions[0]
        assert c["incumbent"] == "temperature"  # native kept
        assert c["rejected"] == "pressure"


class TestBoundedNonConvergence:
    def test_pass_limit_reports_bounded(self, l5x_factory):
        path = l5x_factory(
            tags_xml=tag_xml("C", operand_comments={"": "temp"}),
            rungs_xml=rung_xml(0, "MOV(A,B);") + rung_xml(1, "MOV(B,C);"),
        )
        result = _run(path, config=AnalysisConfig(max_passes=1))
        assert result.convergence_status is ConvergenceStatus.BOUNDED


class TestMigrationPlaceholder:
    def test_placeholder_comment_is_treated_as_uncommented(self, l5x_factory):
        # N101[18] carries a migration placeholder (no real meaning); N18[1] has
        # a genuine comment feeding it. The placeholder operand must be proposed
        # a real, inferred comment rather than being treated as already-commented.
        path = l5x_factory(
            tags_xml=(
                tag_xml("N18", operand_comments={"[1]": "raw temperature"})
                + tag_xml("N101", operand_comments={"[18]": "Generated by Migration Tool"})
            ),
            rungs_xml=rung_xml(0, "ADD(N18[1],1,N101[18]);"),
        )
        result = _run(path)
        decision = _decision_for(result, "N101[18]")
        assert decision is not None, "placeholder operand should get a proposal"
        assert decision["STATUS"] == "inferred"
        assert "temperature" in decision["PROPOSED_DESCRIPTION"].lower()

    def test_real_comment_still_excluded(self, l5x_factory):
        # Control: a genuine comment is still an observation, not a proposal.
        path = l5x_factory(
            tags_xml=tag_xml("N101", operand_comments={"[18]": "real meaning"}),
            rungs_xml=rung_xml(0, "ADD(N18[1],1,N101[18]);"),
        )
        result = _run(path)
        assert _decision_for(result, "N101[18]") is None


class TestProvenanceCarried:
    def test_result_carries_provenance_and_config(self, l5x_factory):
        path = l5x_factory(rungs_xml=rung_xml(0, "MOV(A,B);"))
        result = _run(path)
        assert result.provenance["source_kind"] == "native_l5x"
        assert result.provenance["analysis_config"]["max_passes"] == 8
        assert result.provenance["graph_digest"]
